### PR TITLE
Fix bindings not being saved to state.

### LINKED ISSUE #2: rabbitmq: bindings not being stored in state
_This issue was originally opened by @jason-archidera as hashicorp/terraform#12782. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

I seem to have an issue and it seems to be in saving state.
Version: 0.9
Resource: rabbitmq_binding

I've setup my project with a main.tf:

```
terraform {
    required_version = ">= 0.9"
    backend "consul" {
      address = "XXXXXXXX"
      path    = "tfstate/vhost/xxxxx-development"
  }
}

#######VARIABLES########
variable "endpoint" {
  default = "http://127.0.0.1:15672"
}

variable "username" {
  default = "XXXXX"
}

variable "password" {
  default = "XXXXXX"
}

variable "usersuffix" {
  default = "DEVELOPMENT"
}

variable "vhost" {
  default = "XXXX-DEVELOPMENT-TF"
}

# Configure the RabbitMQ provider
provider "rabbitmq" {
  endpoint = "${var.endpoint}"
  username = "${var.username}"
  password = "${var.password}"
  insecure = true
}

########GET MODULES########
module "create-all" {
    source="./../modules"
    vhost = "${var.vhost}"
    usersuffix = "${var.usersuffix}"
}

#######OUTPUT FOR CONSOLE#######
output "endpoint" {
  value = "${var.endpoint}"
}

output "vhost" {
  value = "${var.vhost}"
}

output "usersuffix" {
  value = "${var.usersuffix}"
}

```
My modules folder has several tf files and all is well except for any binding with a routing key that isn't "#".  For example:

```
resource "rabbitmq_binding" "xxxx_to_zzzz" {
    depends_on = ["rabbitmq_exchange.xxxx", "rabbitmq_queue.zzzzz"]
    source = "XXXX.XXXX"
    vhost = "${rabbitmq_vhost.vhost.name}"
    destination = "XXXX.ZZZZ.Queue"
    destination_type = "queue"
    routing_key = "ZZ.#"
    #routing_key = "#"
    properties_key = "%23"
}

```
I run the commands, everything seems to work, except for the bindings with anything other than "#" are not stored in the remote state (Consul).  This causes each time I run plan or apply, it thinks these bindings are new.   

```
- terraform init -get=true -backend=true

- terraform plan

- terraform apply

```
It's either a bug in the RabbitMQ provider or perhaps in state?   The interesting part is that the bindings are created in RabbitMQ, but the state is not saved.

### PR DESCRIPTION
**Pull request by sgarlick987**
This should fix https://github.com/terraform-providers/terraform-provider-rabbitmq/issues/2 see explanation there for the issue.

Tests ran/passed. I also tested it against our corp env and looks like things are saving properly now.

### CODE REVIEW

File: rabbitmq/resource_binding.go [hunk 1]
```diff
@@ -5,9 +5,9 @@ import (
 	"log"
 	"strings"
 
-	"github.com/michaelklishin/rabbit-hole"
-
 	"github.com/hashicorp/terraform/helper/schema"
+	"github.com/michaelklishin/rabbit-hole"
+	"net/url"
```
Comment (jtopjian) [inline rabbitmq/resource_binding.go]: nit: `net/url` should be inbetween `log` and `strings`.

File: rabbitmq/resource_binding.go [hunk 2]
```diff
@@ -44,12 +44,6 @@ func resourceBinding() *schema.Resource {
 				ForceNew: true,
 			},
 
-			"properties_key": &schema.Schema{
-				Type:     schema.TypeString,
-				Required: true,
-				ForceNew: true,
-			},
```
Comment (jtopjian) [inline rabbitmq/resource_binding.go]: Rather than removing `properties_key` entirely, it should be converted into a read-only computed parameter:

```hcl
"properties_key": &schema.Schema{
	Type:     schema.TypeString,
	Computed: true,
},
```

File: website/docs/r/binding.html.markdown [hunk 3]
```diff
@@ -72,8 +71,6 @@ The following arguments are supported:
 
 * `destination_type` - (Required) The type of destination (queue or exchange).
 
-* `properties_key` - (Required) A unique key to refer to the binding.
```
Comment (jtopjian) [inline website/docs/r/binding.html.markdown:75]: Instead of being removed, this should be moved to the `Attribute Reference` section and listed as an exported attribute.

**Review by jtopjian — CHANGES_REQUESTED** [review]
@sgarlick987 Thanks for putting this together. I've made a few comments. Let me know if you have any questions or if something I suggested is not correct.

File: rabbitmq/resource_binding.go (hunk 1 above)
Comment (sgarlick987) [reply rabbitmq/resource_binding.go]: Sure, for some reason intellij reorged it to the bottom like that, just alpha order is expected?

File: rabbitmq/resource_binding.go (hunk 2 above)
Comment (sgarlick987) [reply rabbitmq/resource_binding.go]: Will do, thanks for the tip.

File: rabbitmq/resource_binding.go (hunk 1 above)
Comment (jtopjian) [reply rabbitmq/resource_binding.go]: Ordering is usually something like: first standard packages, blank space, external packages. See the other files for an example.

**Review by jtopjian — APPROVED** [review]

**Comment by jtopjian** [comment]
This looks good. Thank you again for not just digging into the cause of this issue but putting a fix together for it :)
